### ISSUE TITLE
Decide what software and panels values to allow in the metadata file

### ISSUE THREAD

**Issue by rzetterberg** [BioPsyk/cleansumstats#200]
Me and @pappewaio started discussing about what software and panels we should allow in our metadata files.
Right now the allowed values are not correct, we have the same list of software for both imputation and phasing, we also have the same list of panels for both imputation and phasing.

So what values should you be able to choose for:

- Imputation panel
- Phasing panel
- Imputation software
- Phasing software

Right now these are the values to choose from for both phasing and imputation panels:

```yaml
type: "string"
    enum:
      - "HapMap"
      - "HapMap2"
      - "HapMap3"
      - "1KGP"
      - "TOPMED"
      - "HRC"
      - "meta"
```
    
And these are the values to choose from for both phasing and imputation software:

```yaml
type: "string"
    enum:
      - "plink"
      - "impute"
      - "impute2"
      - "impute3"
      - "shapeIt"
      - "shapeIt2"
      - "shapeIt3"
      - "shapeIt4"
      - "shapeIt5"
      - "MaCH"
      - "Beagle"
      - "Beagle1.0"
      - "meta"
```

CC @AndrewSchork
