### ISSUE TITLE
Providing `study_includedCohorts` in the metadata fails with YAML deserialization error

### ISSUE THREAD

**Issue by rzetterberg** [BioPsyk/cleansumstats#233]
Using the following metadata-file that was produce by the metadata web form: 

```yaml
cleansumstats_version: 0.1.0
cleansumstats_metafile_user: webuser
cleansumstats_metafile_date: '2021-10-29'
stats_neglog10P: false
path_sumStats: iPSYCH2012_ind_F3300.gz
stats_Model: linear
study_includedCohorts:
  - iPSYCH2012
study_Title: Inhouse GWAS iPSYCH2012 F3300
study_PMID: iPSYCH2012_F3300
study_Year: 2020
study_PhenoDesc: Broad depression
path_supplementary: []
study_PhenoCode:
  - EFO:0003761
study_AccessDate: '2021-10-29'
study_Use: restricted
study_Ancestry: EUR
study_Gender: mixed
stats_TraitType: case-control
stats_TotalN: 41866
```

Fails with the following error: 

![2021-10-29-095935_1688x441_scrot](https://user-images.githubusercontent.com/766350/139397949-bc96f823-4c4a-4c98-982b-419533c2074d.png)
