### ISSUE TITLE
Allow `MONDO` ontologies for diseases in the `study_PhenoCode` metadata field

### ISSUE THREAD

**Issue by rzetterberg** [BioPsyk/cleansumstats#337]
The EFO ontology have removed all diseases in favor of using the new Mondo ontology presented in this paper: https://www.medrxiv.org/content/10.1101/2022.04.13.22273750v3. 

That means that no diseases can be found in the `EFO` namespace any longer. For example, schizophrenia was `EFO:0000692` before, but is now obsolete and have been replaced with  `MONDO:0005090`. 

Right now we only allow the `EFO` namespace in [the metadata field `study_PhenoCode`](https://github.com/BioPsyk/cleansumstats/blob/master/assets/schemas/raw-metadata.yaml#L180-L183):

```yaml
    items:
      title: "EFO code"
      type: "string"
      pattern: "^EFO:[0-9]{7}$"
```

This need to be changed into to allow both the `EFO` and `MONDO` namespaces: 

```yaml
    items:
      title: "EFO or MONDO code"
      type: "string"
      pattern: "^EFO|MONDO:[0-9]{7}$"
```
